exercise4: exercise4.cpp hashtable.h linkedlist.h
	@g++ exercise4.cpp -o hastable.h -o linkedlist.h -o exercise4
exercise4.o: exercise4.cpp
	@g++ -o exercise4.o -c exercise4.cpp
clean:
	@rm -f exercise4
	@rm -f exercise4.o