count_components: count_components.cpp digraph.cpp digraph.h
	@g++ count_components.cpp -o digraph.cpp -o digraph.h -o count_components -std=c++11
count_components.o: count_components.cpp
	@g++ -o count_components.o -c count_components.cpp -std=c++11
clean:
	@rm -f count_components.o
	@rm -f count_components